---
version: '3.7'

services:
  bmc-catcher:
    build:
      context: .
    image: metalstack/bmc-catcher:latest
    network_mode: host
    volumes:
      - ${PWD}/dhcpd.leases:/dhcpd.leases
    environment:
      BMC_CATCHER_LEASE_FILE: /dhcpd.leases
      BMC_CATCHER_PARTITION_ID: partition
      BMC_CATCHER_METAL_API_URL: http://localhost:8080
      BMC_CATCHER_METAL_API_HMAC_KEY: test
      BMC_CATCHER_IGNORE_MACS: "aa:aa:aa:aa:aa:aa"

