name: Build image from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Image
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint -b master
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

