name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Figure out if running fork PR
        id: fork
        run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: run -p bugs -p unused

      - name: Set tag
        run: |
          echo "GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        uses: fi-ts/action-docker-make@master
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          args: --no-lint -b release
        if: steps.fork.outputs.is_fork_pr == 'false'

      - name: Only Build
        uses: fi-ts/action-docker-make@master
        with:
          args: --no-lint -b release --no-push
        if: steps.fork.outputs.is_fork_pr == 'true'
