name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set tag
      run: |
        echo "GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
    - name: Docker Image
      uses: metal-stack/action-docker-make@master
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint -b release
