name: Build image from release tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Docker Image
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: --no-lint -b release
