name: Build image from release tag

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2

      - name: Set tag
        run: |
          echo "GIT_TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Docker Image
        uses: fi-ts/action-docker-make@master
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          args: --no-lint -b release
